### PR TITLE
Ligtning update

### PR DESCRIPTION
**Pull request by bbacskay**
The current _Lightning_ effect's code doesn't work correctly with LED stripes longer than 255 LED.
I am using 5m / 300 LED stripe and only the beginning of the stripe is flashing (~first 50 LEDs).

**Solution:**
Change the 'ledstart' and 'ledlen' types from 8bit uint to 16 bit and generate the start position and the length of the lightning using the random16 function.
This would work correctly up to 65535 LEDs in one strip.

### CODE REVIEW

**Comment by pinkywafer** [comment]
Thanks. Is there any reason changing back to `BUILTIN_LED`?

**Comment by pinkywafer** [comment]
Never mind...  it's due to the use of this version of the esp library!...  merging. Thanks

**Comment by bbacskay** [comment]
The reason was just to have a minimal change compared to your code.
In my version I switched to LED_BUILTIN as one of the first changes.

**Comment by pinkywafer** [comment]
Does it still function correctly using led_builtin? If so, I'll happily merge that too... it's more standard.

**Comment by bbacskay** [comment]
It functions correctly. The LED_BUILTIN is the standard Arduino definition.
The BUILTIN_LED is an additional define in the pins_arduino.h files (at least in the ESP32 system):
`#define BUILTIN_LED  LED_BUILTIN // backward compatibility`

I can try to make another PR to change the BUILTIN_LED to LED_BUILTIN, but my GIT knowledge is fairly basic.

**Pull request merged**
