### PR TITLE
Esp32 support

### PR DESCRIPTION
**Pull request by bbacskay**
Tested with DOIT ESP32 DEVKIT V1

### CODE REVIEW

**Comment by pinkywafer** [comment]
That's great.  Can you do a small change - change on / off variables to LED_ON / LED_OFF just so it's clearer what the purpose is of the variable please.
Thanks

**Comment by bbacskay** [comment]
Done.

**Comment by pinkywafer** [comment]
Also, as this is adding more boards support, lets make it version 0.8.0

**Comment by pinkywafer** [comment]
And... can you remove the additional configuration variables for different platforms
As this is intended to be edited by users, I'd rather have the pins defined in only one place. but, include in the comments the recommended pins for different boards

**Pull request merged**
